### ISSUE TITLE
Liens Libs mort

### ISSUE THREAD

**Issue by ghost** [Arinonia/AriLibFX#2]
Bonjour,
Le lien de cette libs http://54.38.169.211/arinonia/AriLibFX-1.0.2.jar est morte sais normal ? merci !

**Comment by FlowArg** [comment]
Probablement pas ;), après, il prépare une grosse nouvelle version, donc ptet qu'il a retiré l'ancienne du dl ? En tout cas si tu veux l'avoir, soit tu la compile toi meme manuellement, soit alors tu peux aller la trouver dans mon repository maven : https://flowarg.github.io/maven/fr/arinonia/arilibfx/1.0.2/arilibfx-1.0.2.jar
Et si tu souhaites les sources pour avoir la doc : 
https://flowarg.github.io/maven/fr/arinonia/arilibfx/1.0.2/arilibfx-1.0.2-sources.jar

**Comment by Arinonia** [comment]
Le lien sera remis à jour dans la journée.
